### ISSUE TITLE
[SEMINAR] overreact, an in silico lab: automative quantum chemical microkinetic simulations for complex chemical reactions

### ISSUE THREAD

**Issue by schneiderfelipe** [geem-lab/seminars#10]
This seminar introduces [**overreact**](https://github.com/geem-lab/overreact), a novel Python package for propagating chemical reactions over time using data from computational chemistry only (*Journal of Computational Chemistry* **2022**, submitted). **overreact** infers all differential equations and parameters from a simple input that consists of a set of chemical equations and quantum chemistry package outputs for each chemical species.

We evaluate some applications from the literature: gas-phase eclipsed-staggered isomerization of ethane, gas-phase umbrella inversion of ammonia, gas-phase degradation of methane by chlorine radical, two solvation-phase reactions, and a simple solvation-phase acid-base equilibrium. We show how it is possible to achieve reaction profiles and information matching experiments.

[Slides](https://github.com/geem-lab/seminars/files/8455321/main.pdf).

**Date**: 2022-03-28

---

**Things to do and check:**

- [x] I inserted the **seminar title** (in the title bar above).
  - [x] I **did not** remove the `[SEMINAR]` part of the title.
- [x] I inserted a **short description** (in this text area above).
- [x] I edited the **date** (in this text area above).
- [x] I assigned the **speaker** (on the right sidebar).
- [x] I ticked those checkboxes either *after* or *while* creating the issue.

> The **date** is when the seminar will take place. If you're unsure about the seminar **speaker**, it's probably *you*.

**Comment by Leticia-maria** [comment]
@schneiderfelipe could you link your slides here? (I would like to use them as reference 😄 )

**Comment by Leticia-maria** [comment]
> Done.

Thank you so much
