### ISSUE TITLE
What happens when we close an issue of seminar proposal?

### ISSUE THREAD

**Issue by Leticia-maria** [geem-lab/seminars#12]
@schneiderfelipe Have you noticed that the seminar no longer appears on the web page when we close the issue?

**Comment by schneiderfelipe** [comment]
I'll take a look, thanks!

**Comment by Leticia-maria** [comment]
It is solved, right?

**Comment by schneiderfelipe** [comment]
Yes.

Em qua, 23 de mar de 2022 18:25, Letícia Maria Pequeno Madureira <
***@***.***> escreveu:
