### ISSUE TITLE
[SEMINAR] Bayesian statistics, structural elucidation and the DP4 probability 

### ISSUE THREAD

**Issue by caprilesport** [geem-lab/seminars#15]
In this seminar the very basics of Bayesian statistics will be presented, followed by a short introduction in the challenges of structure elucidation and the DP4 probability. 

References: 
- (1) [Smith, S. G.; Goodman, J. M. Assigning Stereochemistry to Single Diastereoisomers by GIAO NMR Calculation: The DP4 Probability. J. Am. Chem. Soc. 2010, 132 (37), 12946–12959. ](https://doi.org/10.1021/ja105035r.)
- (2) [Howarth, A.; Ermanis, K.; Goodman, J. M. DP4-AI Automated NMR Data Analysis: Straight from Spectrometer to Structure. Chem. Sci. 2020, 11 (17), 4351–4359.](https://doi.org/10.1039/D0SC00442A.)
- (3) [van de Schoot, R.; Depaoli, S.; King, R.; Kramer, B.; Märtens, K.; Tadesse, M. G.; Vannucci, M.; Gelman, A.; Veen, D.; Willemsen, J.; Yau, C. Bayesian Statistics and Modelling. Nat Rev Methods Primers 2021, 1 (1), 1.](https://doi.org/10.1038/s43586-020-00001-2.)

[Slides](https://github.com/geem-lab/seminars/files/8555796/2022_04_25_DP4_seminar.pptx)

**Date**: 2022-04-25

---

**Things to do and check:**

- [x] I inserted the **seminar title** (in the title bar above).
- [x] I **did not** remove the `[SEMINAR]` part of the title.
- [x] I inserted a **short description** (in this text area above).
- [x] I edited the **date** (in this text area above).
- [x] I assigned the **speaker** (on the right sidebar).
- [x] I ticked those checkboxes either *after* or *while* creating the issue.

> The **date** is when the seminar will take place. If you're unsure about the seminar **speaker**, it's probably *you*.

**Comment by caprilesport** [comment]
@Leticia-maria I cant assign myself, could you do that?

**Comment by schneiderfelipe** [comment]
@caprilesport @Leticia-maria in the future authors will be automatically assigned as per 9c97a31d896a939ad3e2596e4c3ba38e8ba9307e.
