### ISSUE TITLE
If the SEMINAR tag is not the first element of the title, the seminar is not displayed in gh-pages

### ISSUE THREAD

**Issue by caprilesport** [geem-lab/seminars#17]
**Describe the bug**
Title

**To Reproduce**
1. Create a new seminar
2. Insert the seminar title before the [SEMINAR] tag 
3. Wait for gh-pages to deploy

**Expected behavior**
Either warn the user in the create seminar issue template that the [SEMINAR] tag should not be removed and should be the first thing of the title, or detect the tag anywhere in the title

**Comment by schneiderfelipe** [comment]
Closed by 1cc32f8d21e81f0e1b04cec292e17d231ae85562
