### ISSUE TITLE
[SEMINAR] Balmy.jl: Desenvolvimento de Software para Cálculos de Aromaticidade: Implementação com Ambiente Gráfico

### ISSUE THREAD

**Issue by gfcaramori** [geem-lab/seminars#6]
Prévia do Trabalho de Conclusão de Curso do Curso de Graduação em Química do Centro de Ciências Físicas e Matemáticas da Universidade Federal de Santa Catarina para a obtenção do título de bacharel(a) em Química, apresentado por Letícia M. Pequeno Madureira.

Full text: [Leticia Madureira & Giovanni Caramori, **TCC I**](https://github.com/geem-lab/seminars/files/8214688/TCC1_LeticiaMadureira_GiovanniCaramori.pdf).

**Date**: 2022-03-14

---

**Things to do and check:**

- [x] I inserted the **seminar title** (in the title bar above).
  - [x] I **did not** remove the `[SEMINAR]` part of the title.
- [x] I inserted a **short description** (in this text area above).
- [x] I edited the **date** (in this text area above).
- [x] I assigned the **speaker** (on the right sidebar).
- [x] I ticked those checkboxes either *after* or *while* creating the issue.

> The **date** is when the seminar will take place. If you're unsure about the seminar **speaker**, it's probably *you*.

**Comment by schneiderfelipe** [comment]
👏🏽
