### ISSUE TITLE
Show profile picture (if available) in the unfolded details

### ISSUE THREAD

**Issue by schneiderfelipe** [geem-lab/seminars#7]
It would be cool to see who's going to present.
We can just show a profile picture if available.

We could also indicate a path to an image, but checking for a profile pic is simpler for the moment.

**Comment by gfcaramori** [comment]
I think this is a really great idea!

**Comment by schneiderfelipe** [comment]
Closed by b30b2e2175f777948ff6b14399163b1f11f0ea12.
